import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	adjustFontFallback: false,
	fallback: ['system-ui']
});

export const metadata: Metadata = {
	title: "MBOS - Online Navbat Olish",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="uz">
			<body className={`${inter.className} overflow-x-hidden`}>
				{children}
				<div id="modal"></div>
			</body>
		</html>
	);
}

